apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    # If the class annotation is not specified it defaults to "gce".
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
    - http:
        paths:
          - path: /images/*
            backend:
              serviceName: image-ms
              servicePort: 8080
          - path: /ads/*
            backend:
              serviceName: ad-ms
              servicePort: 8080